services:
  redis:
    image: redis:8-alpine
    container_name: sletish_cache
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - sletishCache:/data
    networks:
      - databases

volumes:
  sletishCache:

networks:
  databases:
    driver: bridge
