services:
  redis:
    image: redis:8-alpine
    container_name: sletish_cache
    restart: unless-stopped
    command: redis-server # redis.conf file preferrable for changes, setup later
    ports:
      - "6379:6379"
    volumes:
      - sletishCache:/data
    networks:
      - databases

  postgres:
    image: postgres:17.5-alpine3.21
    container_name: ikoon
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      # Pass ADB variables to the init script
      - ADB_USER=${ADB_USER}
      - ADB_PASS=${ADB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - sletishDB:/var/lib/postgresql/data
      - ./pq-init:/docker-entrypoint-initdb.d:ro,Z
    networks:
      - databases

volumes:
  sletishCache:
  sletishDB:

networks:
  databases:
    driver: bridge
